apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: cyclops-module
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/image-updater-demo
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: my-module-app
  name: module
spec:
  targetNamespace: default
  template:
    path: app-template
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    general:
      environment:
        ENVIRONMENT: production
      image: petarcvit223/logs
      version: 0.0.6
    networking:
      expose: true
      port: 80
      type: ClusterIP
    scaling:
      replicas: 1
status:
  iconURL: https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/static/img/default-template-icon.png?raw=true
  templateResolvedVersion: ab2756886ba4c9e0e3122e3cbb6dc0338fadc617
