apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: cyclops-module
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/image-updater-demo
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  name: module
spec:
  targetNamespace: default
  template:
    path: app-template
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: image-version
  values:
    general:
      environment:
        ENVIRONMENT: production
      image: nginx
    networking:
      expose: true
      port: 80
      type: ClusterIP
    scaling:
      replicas: 1
status: {}
